### ISSUE TITLE
Support for MAC?

### ISSUE THREAD

**Issue by misakichan** [Manisso/fsociety#29]
hi，guy！Support for macOS?

**Comment by mgmgpyaesonewin** [comment]
For me, I install docker on mac first and set up according to the docker.

**Comment by thehappydinoa** [comment]
I would suggest that, but I will work on macOS support. I don't have a real Mac so if I could get some volunteers I could push to a separate branch

**Comment by vasanth3045** [comment]
I fixed this issue and pull request is raised for the same
https://github.com/Manisso/fsociety/pull/30

**Comment by thehappydinoa** [comment]
Ok so I merged your install.sh but that doesn't fix the other issues with the `apt-get install`s that work only for Debian.

**Comment by kdaoudieh** [comment]
- I will be working the few coming days on a new install.sh for Mac OS and will post updates here

**Comment by thehappydinoa** [comment]
Ok, just remembered I just merged one so make sure it's different than that one

**Comment by arjunsalwan** [comment]
Hey, I am new here. Is the MacOS version of this out?

**Comment by JARVIS-AI** [comment]
just for testing
In macOS High Sierra last version, you can use fsociety in two ways :

1. Install on Docker, That need lots of files and capacity about 2GB because of container
2. Install with shell and easy, but it needs **sudo** and if you don't know what are you doing you can  harm your macOS badly

I test both of them, with docker I'm not confident with it because of hosts, network sub domains and all other way to connect docker to real IPs and other network features and options also it take about 2GB, 1.8GB container itself and rest for tools and compiled code like nmap and other features.
And for Shell installation is good but need admin permission and you need run it with sudo.

If you can port it to homebrew or cask or if you don't like to use those scripts you can write if for mac and change the path for not asking the permission and for more security you can use python ENV and put it in install shell and in that way we can install it without sudo permissions,
Then for some features for examples nmap or others that need some admin permissions, we can ask for pass and explain it in during usage.

Now, for me it works in sudo install
i dont know its correct way 
but for now its works
and i know i dont harm my macOS

But it better to use it without admin paths and sudo path in macOS like 
/usr/local/fsociety ===> ~usr/local/fsociety or Homebrew way.

**Comment by CRO-THEHACKER** [comment]
TBH the best way is just to `sudo` it.. Don't worry

**Comment by CRO-THEHACKER** [comment]
I'm going to close this now because of it being a push now.

**Comment by Keoni80** [comment]
> * I will be working the few coming days on a new install.sh for Mac OS and will posting updates here

did you finish the install.sh for macos? thanks!

**Comment by kdaoudieh** [comment]
it's working already @Keoni80  now , please let me know if it dosnt and whats the problem

**Comment by Keoni80** [comment]
> it's working already @Keoni80 now , please let me know if it dosnt and whats the problem

is it? where is te install.sh for macos?

**Comment by CRO-THEHACKER** [comment]
Should work no matter what 
- install.sh is right there in the dir

**Comment by Keoni80** [comment]
start ok, but once u want to use any tools, has issues, please someone with a Mac, can test and tell me if works fine?

**Comment by CRO-THEHACKER** [comment]
I can run it on my Mac. Give me a min.

**Comment by CRO-THEHACKER** [comment]
Working on: darwin Admins-Mac-mini.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by django9659** [comment]
Just got this :/ 

fatal: could not create work tree dir '/usr/local/fsociety': Permission denied
./install.sh: line 77: /usr/local/fsociety/fsociety: No such file or directory
chmod: /usr/local/fsociety/fsociety: No such file or directory
cp: /usr/local/fsociety/fsociety: No such file or directory
cp: /usr/local/fsociety/fsociety.cfg: No such file or directory
rm: /usr/local/fsociety/fsociety: No such file or directory
[✘] Installation failed! [✘] 


anybody got a clue?

**Comment by CRO-THEHACKER** [comment]
You have to use a sudo-user and make sure your in the working dir of f society. I recommend using the new version of fsociety. [here](https://fsociety.dev)

**Comment by frenkie1521** [comment]
If anyone is still wondering how to install Manisso/fsociety for mac here is what I did to get it running on my mac m1:

1. Installed official docker desktop, and did the initial instructions from docket app.
2. Cloned Manisso/fsociety to my tools folder(optional).
3. Followed the step for docker installation from Manisso/fsociety git link.

It automaticly opened for me when i typed "docker-compose exec fsociety fsociety".

Thank you, hope I helped you in someway.
